FROM rustembedded/cross:x86_64-unknown-linux-gnu-0.2.1

RUN apt update && apt install wget software-properties-common apt-transport-https ca-certificates -y
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
RUN apt update && \
apt install llvm-6.0-dev libclang-6.0-dev clang-6.0 libssl-dev pkg-config -y
